"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { ChevronLeftIcon, CopyIcon, SparklesIcon } from "lucide-react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import API from "@/lib/api";

const PROMPT_TEMPLATE = `I want to create a questionnaire form for my SaaS application. I will provide you with some raw data, documents, or a description of what I need.
Please extract the required questions and generate a single JSON object matching this exact schema:

{
  "title": "A short, descriptive title for the form",
  "description": "A brief explanation of the questionnaire (optional)",
  "fields": [
    {
      "type": "TEXT" | "TEXTAREA" | "SELECT" | "RADIO" | "CHECKBOX",
      "label": "The question text",
      "description": "Help text (optional)",
      "required": true | false,
      "options": ["Option 1", "Option 2"] // ONLY include this array if type is SELECT, RADIO, or CHECKBOX
    }
  ]
}

Ensure the fields are logical and use the best field "type" for the question.
Return ONLY the raw JSON output without any markdown formatting, backticks, or explanations.`;

export default function ImportQuestionnairePage() {
  const router = useRouter();
  const [jsonInput, setJsonInput] = useState("");
  const [isImporting, setIsImporting] = useState(false);

  const copyPrompt = () => {
    navigator.clipboard.writeText(PROMPT_TEMPLATE);
    toast.success("Prompt copied to clipboard!");
  };

  const handleImport = async () => {
    if (!jsonInput.trim()) {
      toast.error("Please paste the JSON generated by the AI.");
      return;
    }

    let parsed;
    try {
      parsed = JSON.parse(jsonInput.trim());
    } catch (e) {
      toast.error("Invalid JSON format. Please ensure you copied valid JSON.");
      return;
    }

    if (!parsed.title || !Array.isArray(parsed.fields)) {
      toast.error("JSON is missing required 'title' or 'fields' array.");
      return;
    }

    setIsImporting(true);
    try {
      const res = await API.post("/questionnaires", parsed);
      toast.success("Questionnaire successfully generated!");
      router.push(`/dashboard/questionnaires/${res.data.questionnaire.id}`);
    } catch (error) {
      toast.error(error.response?.data?.error || "Failed to import questionnaire.");
    } finally {
      setIsImporting(false);
    }
  };

  return (
    <div className="p-8 h-full max-w-5xl mx-auto flex flex-col gap-8">
      <div className="flex items-center gap-4 mb-2">
        <Button variant="outline" size="icon" onClick={() => router.push("/dashboard/questionnaires")}>
          <ChevronLeftIcon className="size-4" />
        </Button>
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Import with AI</h1>
          <p className="text-muted-foreground mt-1">Generate a complete questionnaire from raw data using ChatGPT or Claude.</p>
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-8">
        {/* Step 1: Prompt */}
        <Card className="flex flex-col border-primary/20 shadow-sm">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <span className="flex items-center justify-center size-6 rounded-full bg-primary/10 text-primary text-sm font-bold">1</span>
              Copy the Prompt
            </CardTitle>
            <CardDescription>
              Copy this system prompt and paste it into ChatGPT, Claude, or any AI tool, along with your raw text/excel data.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex-1">
            <div className="relative h-full min-h-[300px]">
              <Textarea 
                readOnly 
                value={PROMPT_TEMPLATE} 
                className="h-full resize-none font-mono text-xs bg-muted/30"
              />
            </div>
          </CardContent>
          <CardFooter className="pt-4 border-t">
            <Button onClick={copyPrompt} className="w-full gap-2">
              <CopyIcon className="size-4" /> Copy Prompt to Clipboard
            </Button>
          </CardFooter>
        </Card>

        {/* Step 2: Paste JSON */}
        <Card className="flex flex-col border-primary/20 shadow-sm">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <span className="flex items-center justify-center size-6 rounded-full bg-primary/10 text-primary text-sm font-bold">2</span>
              Paste Generated JSON
            </CardTitle>
            <CardDescription>
              Paste the raw JSON output provided by the AI into the field below to automatically create your form.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex-1">
            <Textarea 
              placeholder='{\n  "title": "Example Form",\n  "fields": [...]\n}'
              value={jsonInput}
              onChange={(e) => setJsonInput(e.target.value)}
              className="h-full min-h-[300px] resize-none font-mono text-xs"
            />
          </CardContent>
          <CardFooter className="pt-4 border-t">
            <Button 
              onClick={handleImport} 
              disabled={isImporting || !jsonInput.trim()} 
              className="w-full gap-2"
            >
              <SparklesIcon className="size-4" /> 
              {isImporting ? "Generating Form..." : "Import Questionnaire"}
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  );
}
